# Generated by Django 3.2.5 on 2021-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_banernews'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='1', max_length=6)),
                ('month', models.CharField(choices=[('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند'), ('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد')], default='mehr', max_length=15)),
                ('year', models.CharField(choices=[('1400', '1400'), ('1401', '1401'), ('1402', '1402'), ('1403', '1403'), ('1404', '1404')], default='1400', max_length=6)),
                ('description', models.TextField(blank=True, default=' ')),
                ('image', models.ImageField(blank=True, default='2.jpg', null=True, upload_to='news/')),
            ],
        ),
    ]
