# Generated by Django 3.2.5 on 2021-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_participate'),
    ]

    operations = [
        migrations.CreateModel(
            name='volenteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('career', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=11)),
                ('address', models.TextField(blank=True, default=' ')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
    ]
