# Generated by Django 3.2.5 on 2021-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0005_volenteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banernews',
            name='description',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='banernews',
            name='title',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
