# Generated by Django 3.2.5 on 2021-12-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0007_auto_20211218_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volenteer',
            name='field',
        ),
    ]
