# Generated by Django 3.2.5 on 2021-12-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0008_remove_volenteer_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volenteer',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'لطفا ایمیل خود را به درستی وارد کنید'}, max_length=254, unique=True),
        ),
    ]
