# Generated by Django 3.2.5 on 2021-12-19 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0009_alter_volenteer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volenteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='لطفا ایمیل خود را به درستی وارد کنید')]),
        ),
    ]
