# Generated by Django 3.2.5 on 2021-12-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0010_alter_volenteer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volenteer',
            name='email',
        ),
    ]
