# Generated by Django 3.2.5 on 2021-12-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0011_remove_volenteer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='month',
            field=models.CharField(choices=[('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند'), ('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور')], default='mehr', max_length=15),
        ),
        migrations.AlterField(
            model_name='participate',
            name='month',
            field=models.CharField(choices=[('مهر', 'مهر'), ('آبان', 'آبان'), ('آذر', 'آذر'), ('دی', 'دی'), ('بهمن', 'بهمن'), ('اسفند', 'اسفند'), ('فروردین', 'فروردین'), ('اردیبهشت', 'اردیبهشت'), ('خرداد', 'خرداد'), ('تیر', 'تیر'), ('مرداد', 'مرداد'), ('شهریور', 'شهریور')], default='mehr', max_length=15),
        ),
    ]
